name: zubat
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: 3.13.6

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  package_info_plus: 4.1.0
  shorebird_code_push: 1.1.2
  shimmer: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - shorebird.yaml
